### ISSUE TITLE
Set user agent for pdb dowbload

### ISSUE THREAD

**Issue by javieriserte** [diegozea/MIToS.jl#24]
Add option:
-A "Mozilla/5.0 (compatible; MSIE 7.01; Windows NT 5.0)"
to curl to emulate browser if normal download gives error 503 (service unavailable).

https://curl.haxx.se/docs/httpscripting.html#User_Agent
http://osxdaily.com/2011/07/16/change-user-agent-with-curl/
http://www.dougsparling.org/setting-user-agent-curl-wget/

**Comment by diegozea** [comment]
MIToS 2.0 introduces a `download_file` in the `Utils` module. `download_file` calls the `get_streaming` function of the [Requests](https://github.com/JuliaWeb/Requests.jl) package using the same keyword arguments. So, you can use the `header` argument to set the user agent using a `Dict`. That keyword argument will be also available in `downloadpdb`, because that function calls `download_file`. So, the following line does is going to do the magic in the future release of MIToS (2.1.1) ;)

```julia
downloadpdb("1IVO", headers=Dict("User-Agent" => "Mozilla/5.0 (compatible; MSIE 7.01; Windows NT 5.0)"))
```
