### ISSUE TITLE
Some overloads violate function intent

### ISSUE THREAD

**Issue by timholy** [diegozea/MIToS.jl#79]
Some of the overloads of Base methods violate the intended API of the function. For example, `print(x, y, z...)` should print all of `x`, `y`, and `z` to the terminal, yet we have methods that add a format argument that isn't displayed:
- https://github.com/diegozea/MIToS.jl/blob/717d6f9306ca743ed66f0f94c023fcbeb47c00d4/src/MSA/FASTA.jl#L97
- https://github.com/diegozea/MIToS.jl/blob/717d6f9306ca743ed66f0f94c023fcbeb47c00d4/src/MSA/Raw.jl#L72
- https://github.com/diegozea/MIToS.jl/blob/717d6f9306ca743ed66f0f94c023fcbeb47c00d4/src/PDB/PDBParser.jl#L301

By comparison:
```julia
julia> print("Hello", Float32)
HelloFloat32
```

The way that Base intends you to customize output of `print` is with an `IOContext` wrapper around the `io` object.

**Comment by diegozea** [comment]
Hi @timholy !

I think I will change the `read` , `parse` and `write` and `print` for `(something, FileFormat)`, to `read_file`, `parse_file`, `print_file`, and `write_file`, respectively. Do you think that's a better approach?

Cheers,

**Comment by diegozea** [comment]
Hi!

MIToS 2.18 now defines the `read_file`, `parse_file`, `print_file`, and `write_file` functions for reading and writing in specific file formats—subtypes of `FileFormat`—instead of overloading the functions from `Base`. The signatures and behaviors don't change, so the migration will require replacing `read` with `read_file` and so on. So, for example `read(msafile, FASTA)` becomes `read_file(msafile, FASTA)`.

Cheers
